main = ".open-next/worker.js"
name = "nuco"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

# Hyperdrive configuration
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "nuco-hyperdrive"