import { BaseExportAgent, ExportConfig, ExportMetadata } from './base';
import { AIServiceError } from '@/lib/ai/error';
import { AgentContext, AgentResult } from '@/lib/ai/agents/base';
import { ChartJSNodeCanvas } from 'chartjs-node-canvas';
import PDFDocument from 'pdfkit';
import { gzip } from 'zlib';
import { promisify } from 'util';
import {
  ChartConfiguration,
  ChartType,
  ChartData,
  ScaleOptionsByType,
  CartesianScaleTypeRegistry,
  GridLineOptions,
  CartesianScaleOptions,
  CategoryScaleOptions,
  LinearScaleOptions,
  Color,
  Align,
  FontSpec,
} from 'chart.js';
import { BaseAgent, AgentConfig } from '@/lib/ai/agents/base';
import { AIService } from '@/lib/ai/service';

const gzipAsync = promisify(gzip);

interface PDFOptions {
  pageSize?: 'A4' | 'Letter' | 'Legal';
  orientation?: 'portrait' | 'landscape';
  margins?: {
    top: number;
    right: number;
    bottom: number;
    left: number;
  };
  header?: {
    text: string;
    fontSize?: number;
    color?: string;
  };
  footer?: {
    text: string;
    fontSize?: number;
    color?: string;
  };
}

interface ChartConfig {
  type: ChartType;
  data: ChartData;
  options?: Record<string, unknown>;
  width?: number;
  height?: number;
}

export class PDFExportAgent extends BaseExportAgent {
  private chartJSNodeCanvas: ChartJSNodeCanvas;
  private defaultOptions: PDFOptions = {
    pageSize: 'A4',
    orientation: 'portrait',
    margins: {
      top: 50,
      right: 50,
      bottom: 50,
      left: 50,
    },
    header: {
      text: 'Analysis Report',
      fontSize: 20,
      color: '#000000',
    },
    footer: {
      text: 'Generated by Neuco AI',
      fontSize: 10,
      color: '#666666',
    },
  };

  constructor() {
    const config: AgentConfig = {
      id: 'pdf-export',
      name: 'PDF Export Agent',
      description: 'Agent for exporting data to PDF format',
      model: 'gpt-4',
      aiService: new AIService(), // Will be overridden in initialize
    };
    super(config);
    this.chartJSNodeCanvas = new ChartJSNodeCanvas({
      width: 800,
      height: 400,
      backgroundColour: '#ffffff',
    });
  }

  protected async formatData(data: unknown): Promise<Buffer> {
    const doc = new PDFDocument();
    const chunks: Buffer[] = [];
    
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    
    if (Array.isArray(data)) {
      for (const item of data) {
        if (typeof item === 'string') {
          doc.text(item);
        } else {
          doc.text(JSON.stringify(item, null, 2));
        }
        doc.moveDown();
      }
    } else {
      doc.text(JSON.stringify(data, null, 2));
    }
    
    doc.end();
    
    return new Promise((resolve, reject) => {
      doc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });
      doc.on('error', reject);
    });
  }

  async execute(context: AgentContext): Promise<AgentResult> {
    try {
      const config = context.metadata.config as ExportConfig;
      await this.validateConfig(config);

      const cacheKey = this.generateCacheKey(context.metadata.data, context.metadata);
      
      // Check cache first
      const cachedResult = await this.redis.get(cacheKey);
      if (cachedResult) {
        return {
          success: true,
          output: cachedResult,
          metadata: {
            ...context.metadata,
            export: {
              status: 'completed',
              timestamp: new Date().toISOString(),
              format: 'pdf',
              source: 'cache',
            } as ExportMetadata,
          },
        };
      }

      // Generate PDF
      const pdfBuffer = await this.generatePDF(context.metadata.data, config);
      
      // Compress if requested
      let finalData = pdfBuffer;
      let size = pdfBuffer.length;
      let isCompressed = false;
      
      if (config.options?.compression) {
        const compressed = await this.compress(pdfBuffer);
        finalData = Buffer.from(compressed, 'base64');
        size = finalData.length;
        isCompressed = true;
      }

      const result = {
        success: true,
        output: finalData,
        metadata: {
          ...context.metadata,
          export: {
            status: 'completed',
            timestamp: new Date().toISOString(),
            format: 'pdf',
            size,
            isCompressed,
          } as ExportMetadata,
        },
      };

      // Cache result
      await this.redis.set(cacheKey, result, { ex: this.cacheTTL });

      // Store result in database
      if (context.metadata.id) {
        await this.storeExportResult(context.metadata.id as string, {
          format: 'pdf',
          data: finalData,
          metadata: result.metadata.export as ExportMetadata,
        });
      }

      return result;
    } catch (error) {
      const err = error instanceof Error ? error : new Error(String(error));
      console.error('PDF export error:', err);
      return {
        success: false,
        output: null,
        error: err,
        metadata: context.metadata,
      };
    }
  }

  protected async validateConfig(config: ExportConfig): Promise<void> {
    if (!config.format || config.format !== 'pdf') {
      throw new AIServiceError('Invalid export format. Expected "pdf"');
    }
  }

  private async generatePDF(data: unknown, config: ExportConfig): Promise<Buffer> {
    const options = { ...this.defaultOptions, ...config.options };
    const doc = new PDFDocument({
      size: options.pageSize,
      layout: options.orientation,
      margins: options.margins,
    });

    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    // Add header
    if (options.header) {
      doc.fontSize(options.header.fontSize || 20)
         .fillColor(options.header.color || '#000000')
         .text(options.header.text, { align: 'center' })
         .moveDown();
    }

    // Add content
    if (Array.isArray(data)) {
      // Generate charts if data contains chart configurations
      const chartData = data.filter(item => 
        typeof item === 'object' && item !== null && 'type' in item
      ) as ChartConfig[];

      for (const chart of chartData) {
        const image = await this.generateChart(chart);
        doc.image(image, {
          fit: [doc.page.width - doc.page.margins.left - doc.page.margins.right, 300],
          align: 'center',
        });
        doc.moveDown();
      }

      // Add text content
      const textData = data.filter(item => 
        typeof item === 'string' || 
        (typeof item === 'object' && item !== null && !('type' in item))
      );

      for (const item of textData) {
        if (typeof item === 'string') {
          doc.text(item);
        } else {
          doc.text(JSON.stringify(item, null, 2));
        }
        doc.moveDown();
      }
    } else {
      doc.text(JSON.stringify(data, null, 2));
    }

    // Add footer
    if (options.footer) {
      doc.fontSize(options.footer.fontSize || 10)
         .fillColor(options.footer.color || '#666666')
         .text(options.footer.text, { align: 'center' });
    }

    // Finalize PDF
    doc.end();

    // Wait for all chunks to be collected
    return new Promise((resolve, reject) => {
      doc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });
      doc.on('error', reject);
    });
  }

  private async generateChart(config: ChartConfig): Promise<Buffer> {
    // Note: Chart.js types are very strict and don't perfectly match the runtime behavior
    // We use type assertion here to work around the type system limitations
    const chart = {
      type: config.type,
      data: config.data,
      options: {
        ...config.options,
        animation: false,
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: {
            position: 'top',
            labels: {
              boxWidth: 12,
              padding: 10,
            },
            display: true,
          },
          tooltip: {
            mode: 'index',
            intersect: false,
          },
        },
        scales: this.getChartScales(config.type),
      },
    } as ChartConfiguration;

    // Set specific chart options based on type
    if (config.type === 'doughnut') {
      (chart.options as any).cutout = '50%';
    }

    return await this.chartJSNodeCanvas.renderToBuffer(chart);
  }

  private getChartScales(type: ChartType): Record<string, ScaleOptionsByType<keyof CartesianScaleTypeRegistry>> | undefined {
    // Note: Chart.js types are very strict and don't perfectly match the runtime behavior
    // We use type assertion here to work around the type system limitations
    // The actual runtime behavior is correct, but the types are overly restrictive
    const defaultGridOptions = {
      display: true,
      drawBorder: true,
      drawOnChartArea: true,
      borderColor: '#e0e0e0' as Color,
      borderWidth: 1,
      borderDash: [],
      borderDashOffset: 0,
      circular: false,
      color: '#e0e0e0' as Color,
      drawTicks: true,
      tickColor: '#e0e0e0' as Color,
      tickLength: 5,
      tickWidth: 1,
      tickBorderDash: [],
      tickBorderDashOffset: 0,
      lineWidth: 1,
      z: 0,
      offset: false,
    } as GridLineOptions;

    const defaultTitleOptions = {
      display: false,
      align: 'center' as Align,
      text: '',
      color: '#666666' as Color,
      font: {
        size: 12,
        weight: 'bold',
      } as FontSpec,
      padding: 4,
    };

    const defaultTicksOptions = {
      display: true,
      align: 'center' as Align,
      crossAlign: 'near' as Align,
      showLabelBackdrop: false,
      backdropColor: 'transparent' as Color,
      backdropPadding: 0,
      color: '#666666' as Color,
      font: {
        size: 10,
      } as FontSpec,
      padding: 4,
      textStrokeColor: '' as Color,
      textStrokeWidth: 0,
      z: 0,
      major: {
        enabled: false,
      },
      callback: function(this: any, value: string | number) {
        return value.toString();
      },
    };

    const defaultScaleOptions = {
      display: true,
      position: 'bottom',
      grid: defaultGridOptions,
      title: defaultTitleOptions,
      ticks: defaultTicksOptions,
    };

    const defaultCategoryOptions = {
      ...defaultScaleOptions,
      type: 'category' as const,
      position: 'bottom',
      bounds: 'data',
      offset: false,
      reverse: false,
      min: 0,
      max: 0,
      labels: [],
    } as unknown as CategoryScaleOptions;

    const defaultLinearOptions = {
      ...defaultScaleOptions,
      type: 'linear' as const,
      position: 'left',
      bounds: 'data',
      offset: false,
      reverse: false,
      min: 0,
      max: 0,
      beginAtZero: true,
    } as unknown as LinearScaleOptions;

    // Note: We use a double type assertion here to work around Chart.js's strict type system
    // The actual runtime behavior is correct, but the types are overly restrictive
    const result = (() => {
      switch (type) {
        case 'bar':
          return {
            x: {
              ...defaultCategoryOptions,
              grid: {
                ...defaultGridOptions,
                display: false,
                drawBorder: false,
                drawOnChartArea: false,
              },
            },
            y: {
              ...defaultLinearOptions,
            },
          };
        case 'line':
          return {
            x: {
              ...defaultCategoryOptions,
            },
            y: {
              ...defaultLinearOptions,
            },
          };
        case 'scatter':
          return {
            x: {
              ...defaultLinearOptions,
            },
            y: {
              ...defaultLinearOptions,
            },
          };
        case 'bubble':
          return {
            x: {
              ...defaultLinearOptions,
            },
            y: {
              ...defaultLinearOptions,
            },
          };
        case 'radar':
          return {
            r: {
              ...defaultLinearOptions,
              position: 'chartArea',
            },
          };
        case 'polarArea':
          return {
            r: {
              ...defaultLinearOptions,
              position: 'chartArea',
            },
          };
        default:
          return undefined;
      }
    })() as unknown as Record<string, ScaleOptionsByType<keyof CartesianScaleTypeRegistry>> | undefined;

    return result;
  }

  private async compress(data: Buffer): Promise<string> {
    try {
      const compressed = await gzipAsync(data);
      return compressed.toString('base64');
    } catch (error) {
      console.error('Compression failed:', error);
      return data.toString('base64'); // Fallback to base64 without compression
    }
  }
} 